---
- name: Pre-Check for Existing Firewall Policy
  hosts: all # This playbook will be delegated to specific Palo Alto hosts
  #hosts: "{{ firewalls | join(',') }}" # Target firewalls identified in the path
  gather_facts: no
  connection: network_cli
  collections:
    - paloaltonetworks.panos

  vars:
    check_source_ip: "{{ source_ip }}"
    check_destination_ip: "{{ destination_ip }}"
    check_protocol: "{{ protocol }}"
    check_port: "{{ port }}"

    # Flag to indicate if a policy is found on this firewall
    policy_found_flag: false

    # Map protocol names to numbers for Palo Alto `test security-policy-match` command
    pa_protocol_number: "{{ { 'tcp': 6, 'udp': 17, 'icmp': 1, 'any': 'any' }[check_protocol | lower] | default(check_protocol) }}"

  tasks:
    - name: Debug Pre-Check variables
      debug:
        msg: "Pre-checking for existing policy on {{ inventory_hostname }} for Source: {{ check_source_ip }}, Dest: {{ check_destination_ip }}, Proto: {{ check_protocol }}, Port: {{ check_port }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Run Palo Alto Security Policy Match
      paloaltonetworks.panos.panos_op:
        provider:
          ip_address: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          api_key: "{{ ansible_api_key | default(omit) }}"
        cmd: "<test><security-policy-match><source>{{ check_source_ip }}</source><destination>{{ check_destination_ip }}</destination><protocol>{{ pa_protocol_number }}</protocol><destination-port>{{ check_port }}</destination-port></security-policy-match></test>"
        cmd_is_xml: true
      register: pa_policy_match_output
      when: inventory_hostname in groups['paloalto'] | default([])
      ignore_errors: yes

    - name: Debug Palo Alto Policy Match Output
      debug:
        var: pa_policy_match_output
      when: inventory_hostname in groups['paloalto'] | default([]) and pa_policy_match_output is defined

    - name: Set policy_found_flag if Palo Alto policy matches
      set_fact:
        policy_found_flag: true
      when:
        - inventory_hostname in groups['paloalto'] | default([])
        - pa_policy_match_output is defined
        - pa_policy_match_output.stdout_xml is defined
        # Check if the output contains a rule name that is NOT "No matching rule found"
        - pa_policy_match_output.stdout_xml | regex_search('<entry name="([^"]+)"')
        - not (pa_policy_match_output.stdout_xml | regex_search('<entry name="No matching rule found"'))
      run_once: true
      delegate_to: localhost

    - name: Indicate if policy was found
      debug:
        msg: "POLICY_EXISTS"
      when: policy_found_flag
      run_once: true
      delegate_to: localhost
