---
- name: FortiGate Pre-Check for Existing Firewall Policy
  hosts: "{{ firewall_name }}"
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios

  vars:
    check_source_ip: "{{ source_ip }}"
    check_destination_ip: "{{ destination_ip }}"
    check_protocol: "{{ protocol }}"
    check_port: "{{ port }}"
    policy_found_flag: false

  tasks:
    - name: Debug FortiGate Pre-Check variables
      debug:
        msg: "Pre-checking for existing policy on {{ inventory_hostname }} (FortiGate) for Source: {{ check_source_ip }}, Dest: {{ check_destination_ip }}, Protocol: {{ check_protocol }}, Port: {{ check_port }}"

    - name: Policy Lookup via API
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/api/v2/monitor/firewall/policy-lookup/?access_token={{ fortinet_api_key }}&srcintf=port3&sourceip={{ check_source_ip }}&protocol={{ check_protocol }}&dest={{ check_destination_ip }}&destport={{ check_port }}"
        method: GET
        validate_certs: no
        return_content: yes
      register: fgt_policy_lookup_result
      ignore_errors: yes

    - name: Set policy_found_flag based on API lookup result
      set_fact:
        policy_found_flag: true
      when: fgt_policy_lookup_result.status == 200 and fgt_policy_lookup_result.json.results.match | default(false) == true
      run_once: true
      delegate_to: localhost

    - name: Indicate if policy was found
      debug:
        msg: "POLICY_EXISTS"
      when: policy_found_flag
      run_once: true
      delegate_to: localhost
