---
- name: FortiGate Provision Firewall Rule
  hosts: "{{ firewall_name }}"
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortios
  any_errors_fatal: true

  vars:
    rule_id: "{{ rule_id }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    protocol: "{{ protocol }}"
    dest_port: "{{ dest_port }}"
    rule_description: "{{ rule_description }}"
    src_addr_name: "h-{{ source_ip }}"
    dst_addr_name: "h-{{ destination_ip }}"
    fortigate_service_name: "{{ (protocol | upper) ~ '-' ~ (dest_port | replace('-', '_')) if protocol | lower not in ['any', 'icmp'] else ('ALL_ICMP' if protocol | lower == 'icmp' else 'ALL') | trim }}"

  tasks:
    - name: Debug Provisioning variables
      debug:
        msg: "Provisioning Rule ID: {{ rule_id }} on {{ inventory_hostname }} (FortiGate) for Source: {{ source_ip }}, Destination: {{ destination_ip }}, Protocol: {{ protocol }}, Port: {{ dest_port }}"

    - name: Create Source Address Object
      fortinet.fortios.fortios_firewall_address:
          vdom: "root"
          state: "present"
          access_token: "{{ fortinet_api_access_token }}"
          firewall_address:
              name: "{{ src_addr_name }}"
              subnet: "{{ source_ip }}/32"
              type: "ipmask"

    - name: Create Destination Address Object
      fortinet.fortios.fortios_firewall_address:
          vdom: "root"
          state: "present"
          access_token: "{{ fortinet_api_access_token }}"
          firewall_address:
              name: "{{ dst_addr_name }}"
              subnet: "{{ destination_ip }}/32"
              type: "ipmask"

    - name: Create Service Object (TCP)
      when:
          - protocol | lower == 'tcp'
      fortinet.fortios.fortios_firewall_service_custom:
          vdom: "root"
          state: "present"
          access_token: "{{ fortinet_api_access_token }}"
          firewall_service_custom:
               name: "{{ fortigate_service_name }}"
               protocol: "TCP/UDP/SCTP"
               tcp_portrange: "{{ dest_port }}"

    - name: Create Service Object (UDP)
      when:
          - protocol | lower == 'udp'
      fortinet.fortios.fortios_firewall_service_custom:
          vdom: "root"
          state: "present"
          access_token: "{{ fortinet_api_access_token }}"
          firewall_service_custom:
               name: "{{ fortigate_service_name }}"
               protocol: "TCP/UDP/SCTP"
               udp_portrange: "{{ dest_port }}"

    - name: Create Firewall Policy
      fortinet.fortios.fortios_firewall_policy:
          vdom: "root"
          state: "present"
          access_token: "{{ fortinet_api_access_token }}"
          firewall_policy:
              name: "firework-{{ rule_id }}"
              policyid: "{{ rule_id }}"
              srcintf:
                  - name: "any"
              dstintf:
                  - name: "any"
              srcaddr:
                  - name: "{{ src_addr_name }}"
              dstaddr:
                  - name: "{{ dst_addr_name }}"
              service:
                  - name: "{{ fortigate_service_name }}"
              action: "accept"
              schedule: "always"
              logtraffic: "all"
              comments: "firework-{{ rule_id }}"
