"""Initial Firework app schema

Revision ID: 358b2f854abc
Revises: 
Create Date: 2025-07-12 12:04:15.511932

"""
from alembic import op
import sqlalchemy as sa
from app.models import JSONEncodedList


# revision identifiers, used by Alembic.
revision = '358b2f854abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('destination_ip', sa.String(length=50), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('destination_port', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_resource_id', sa.Integer(), nullable=True),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arp_entries',
    sa.Column('arp_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=False),
    sa.Column('interface_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('arp_id')
    )
    op.create_table('firewall_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('destination_ip', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('ports', JSONEncodedList(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approver_comment', sa.Text(), nullable=True),
    sa.Column('implementer_id', sa.Integer(), nullable=True),
    sa.Column('implementer_comment', sa.Text(), nullable=True),
    sa.Column('firewalls_involved', JSONEncodedList(), nullable=True),
    sa.Column('firewalls_to_provision', JSONEncodedList(), nullable=True),
    sa.Column('firewalls_already_configured', JSONEncodedList(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['implementer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interfaces',
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ipv4_address', sa.String(length=50), nullable=True),
    sa.Column('ipv4_subnet', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('interface_id')
    )
    op.create_table('route_entries',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('destination_network', sa.String(length=50), nullable=False),
    sa.Column('next_hop', sa.String(length=50), nullable=True),
    sa.Column('metric', sa.Integer(), nullable=True),
    sa.Column('admin_distance', sa.Integer(), nullable=True),
    sa.Column('interface_name', sa.String(length=100), nullable=True),
    sa.Column('route_type', sa.String(length=50), nullable=True),
    sa.Column('flags', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_entries')
    op.drop_table('interfaces')
    op.drop_table('firewall_rule')
    op.drop_table('arp_entries')
    op.drop_table('activity_log_entry')
    op.drop_table('user')
    op.drop_table('devices')
    op.drop_table('blacklist_rule')
    # ### end Alembic commands ###
