"""Initial schema for Firework app

Revision ID: 4a026da3919d
Revises: 
Create Date: 2025-06-05 13:09:56.901483

"""
from alembic import op
import sqlalchemy as sa
from app.models import JSONEncodedList


# revision identifiers, used by Alembic.
revision = '4a026da3919d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('destination_ip', sa.String(length=50), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('destination_port', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('firewall_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('destination_ip', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approver_id', sa.String(length=50), nullable=True),
    sa.Column('approver_comment', sa.Text(), nullable=True),
    sa.Column('firewalls_involved', JSONEncodedList(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firewall_rule')
    op.drop_table('blacklist_rule')
    # ### end Alembic commands ###
